### ISSUE TITLE
【有趣项目】讨论

### ISSUE THREAD

**Issue by Hailiange** [BP-amusing/BP-#2]
## 我的一些想法：

你混在有趣的人中，你的世界就有趣。王小波说，我活在世上，无非想要明白些道理，遇见些有趣的事。倘能如我所愿，我的一生就算成功。咱们这个项目的初衷就是让更多的人明白些道理（有趣的故事），遇见有趣的事（有趣的人以及他们做的事），去过有趣的人生。

每一位有趣的人都是一颗天上的星。有趣对抗现实。

所以，项目暂以「有趣青年」命名，对应「有志青年」。

Edge.org的宗旨是“To arrive at the edge of the world's knowledge, seek out the most complex and sophisticated minds, put them in a room together, and have them ask each other the questions they are asking themselves.”

咱们的宗旨是汇聚有趣的人和有趣的故事，让「有趣」相互问候、交流、碰撞和传染。以故事交换故事，以成长促进成长。

计划是以线上网站或实体俱乐部为载体。俱乐部里汇聚一大群「有趣的人」和流传着的「有趣故事」。俱乐部是开放的。任何有趣的人都可以在俱乐部里分享自己有趣的故事，他人通过听故事学习模仿，让更多人去做「有趣的人」，过「有趣的生活」。

我们认为有趣是生命第一要义。要把生命浪费在美好的事物上。
- 原理：主要利用记忆生存优势（社会交换）和人类喜欢故事和惊奇
### 可能应用场景：

咖啡馆，饮料馆之类的场所，客栈、旅馆

这里以有趣的人、有趣的故事为主。不过不是卖咖啡饮料，而是故事，在这里故事是货币，只要你讲述你有趣的故事，在这里1星期或者1天的消费就免单，费用由听众出。
- 构想：过去客栈就是信息、小道消息流通的场所，还是各地旅人、流浪诗人，游吟诗人汇聚的场所，现在，咱们可以将古代客栈的这种功能还原、复古。

这是一个共创的客栈。世界上的每一个有趣的人都天然是这家「客栈」、「基地」的主人。愿意出钱就出钱，愿意出力就出力，名字会收入「有趣贡献榜」、兑换「故事币」。
### 频次

固定时期：有趣星期六  每周一次有趣对对碰；或者更长时间每10天一次
召集有趣的人，有趣的故事，有意义的场景。
### 进门招牌就是：
- 你今天做了哪三件有趣的事?
- 你一生发生过有趣的事吗?
- 你认为在你的过往里，做到最有趣的事是什么?
- 每个人都有自己都是故事，你的故事是什么?
- 这里有趣的故事就是你通行的货币

有困惑了，来听故事；想聊天了，来讲故事；想交朋友了，来谈故事；

问问你自己，你一天中有三间有趣事吗？
你是一个有趣的人吗？

内在富足的人不会为生活所困，因为他可以只用内在的“丰盛富足”，就能够与任何人做到价值上的“交换”了。而内心匮乏的人，只能用「金钱」来当货币，无趣到只剩下了金钱，甚至有的人连金钱也没有。

这里，欢迎内心富足的人来让更多的人内心富足。欢迎自觉无趣的人变得有趣。

**Comment by Hailiange** [comment]
### 有关 「有趣」的界定、盈利模式、会员困境的问题

> 本讨论是海良与吴楠在4月1日「有趣青年」BP群讨论整理而成。探讨的主要有关「有趣」的界定、盈利模式、组织场景、会员少的问题。这是一场「有心流」的对话讨论。吴楠3+2问。
- 时间：4月1日 23：00
- 地点：「有趣青年」召唤神龙团队
- 人物：吴楠(Jerome ) &  张海良 (阳光36度)  
- 对应：吴-吴楠(Jerome )  &  张- 张海良 (阳光36度)
- 记录：

#### 「有趣」的界定、无人可请、规模盈利的问题

吴：以故事切入挺好的，那有几个问题：

第一，什么样的故事算是有趣？如果有人过来 ，听完你的分享 觉得无趣 ，怎么办？你的有趣的标准是什么？ 
第二，读书会里，绝大多数人是不读书的。也就是说，很多人是没什么故事的。这点怎么解决。 
第三，怎么实现规模？然后盈利？

个人浅见，还请多指点。

张： 我试着回答下：

问题一：我的解决方案是投票。把权利给听众，10个人里感觉， 10个人里面5-6个人感觉这个故事有趣，感觉有意义，对自己有启发和触动，对自己有帮助，有意义即视为有趣。

问题二：我们不组织读书会。只组织故事会。每一个人的故事就是他本人的人生经历，你用30到60或者90分钟的时间，阅读去经历他的人生，用这么短时间去阅读这个人，他是生动的。不是死的“书” 。

问题三：规模化是以后的事情，最起码一线城市、国际城市都可以容纳这样开放的空间。盈利来源：场地有咖啡、饮食、图书等。

更重要的是建立起让听众为我们和讲者付费。我们就是要有趣的人，无趣的人只是为有趣的支付货币。
毕竟，你到哪里去找这样一个肯花时间让你进入别人世界的机会。可以用一天的时间度过2-3个人的人生？！

另外，我上面也说了：这是一个共创的客栈。世界上的每一个有趣的人都天然是这家「客栈」、「基地」的主人。愿意出钱就出钱，愿意出力就出力，名字会收入「有趣贡献榜」、兑换「故事币」。 这里流通的是故事币，不是金钱。

> - 开放是灵魂 
> - 有趣是骨架 
> - 故事是血肉 
> - 人物是血液 
> - 故事货币是粮食 
> - 铁打的营流水的兵，流动是常态。

以上就是我的思考解答。 

#### 线下活动参加人数稀少、会员的流失、规模的问题

吴：恩。

> 问题一：我的解决方案是投票。把权利给听众，10个人里感觉，这个故事有趣，对自己有启发和触动，有意义即视为有趣。

投票是能够选择故事是否有趣的一个衡量指标。 这点没问题。

但是，投票是发生在故事讲完的基础上，而故事好不好是在人听完后就马上已经有判断了。故事讲的好不好，可能会直接影响到听众对于这个活动本身的看法上，如果看法是负面的，那就可能意味着你失去了一个甚至是多个的[会员] 

张：是的，由投票确定“有趣”。我们不定义“有趣”，让听众去定义 。

另外，大部分的故事活动是由分享人发起的，我们是个平台，（我们组织活动除外）或者是由听众点名的，我们寻找的。

关于你说的「流失」问题，我认为，不要只盯着一个故事活动，像股市和海浪，有起有伏才是常态。我的理解，你既然想要一个活动赢得多个会员，那里就要有准备，一个活动失去多个会员的考虑。阴阳两面的一体的，总的体态是多>失。 

吴：其实有个比较大的问题，线下活动的时候，如果你给别人是一个虚的概念，参加的人就会比较少 。

张：一开始不会要求人多的，能有几个人进行小型聚会就可以了。 我当初想还是进行“深度交流”的，而不是泛泛而谈。而且人少会更有感觉，分享者会更放的开。

吴：也就是说，你想的是 一开始你拉过来组织的人，都是比较高水平的吧啊 

张：最少3个人的思想水平±1，最小单位是3人，2人容易陷入静默，3人刚好。33小组 

一组人数3、5、7、9。 不会一开始大规模的 ，我甚至还想要搞的神秘些呢。限定人数、限定场次。人多了反而有顾忌，毕竟还会涉及到隐私，人少更容易增进感情和信任。 

吴：你这样 做大不是,做小了更不好了，会有这样的矛盾。

张：先从一个样板起来，再开下一个。一个场地可以有2-3个故事小组呀，当然中间会隔开。不一定一个场地只有1个。 这样呢 。甚至可以有户外的形式 。

#### 项目所有设定的前提、线下活动冷清的问题

吴：那这种形式 不是更像是一个交友的平台 

张：是呀，不过，我们不管他们的交友与否，我们只管他们此时、此刻、此地在这里发生的故事以及交换。我们还可以是一个故事原料出版平台，每一个故事依主题集结出版，送给讲者和听众，卖给市场，这也是一大收入来源 。

吴：你组织个活动，把人叫过来。然后让他们交流，告诉他们 ，你们交流是交流你们有趣的故事。是这样的没错吧 。

张：

是的。
对的，从他人故事中看见成长的自己 

看见未来的自己 ，你走过的路，有可能是我下一步要走的；或者说，是我要引以为戒的 

> - 通过人筛选过滤信息 
> - 通过故事组织信息
> - 通过促发触动产生交换 
> - 以心换心 

可以说，每加入一人都是他自己的财富，而不是别人的 

吴：  你所有设定的前提,都是

1）邀请来的人，都是 会讲故事的，有故事的。愿意分享自己的 故事的人 
2）必须讲故事，还是有趣的故事。 

但是有趣这个概念，很多人都想，但是绝大多数人多有趣这个词是没什么概念的。也就是说，有趣是个模糊的概念。人的大脑对模糊的概念，没有那么多的精确概念 。线下的活动，为什么我们（友趣）不会以「有趣」的名义而更多的是以一个具体的活动来落实，就是因为如果用有趣的名义，来的人会很少啊。

张： 

1）不一定要绘声绘色，最起码要有真情实感。就是要找这种真诚的人，因为不真诚的人太多的，真诚的人反而更珍贵 

2）是的，人脑对有趣的概念不是太清晰。但以故事为载体，一个故事最起码的特质就是有逆转，有因果，我感觉他天然蕴含着有趣。

你说的线下活动无法用「有趣」的问题。我认为可以具体到有趣的一件事。比如，有趣的一次旅行，有趣的一次见面，有趣的一次学习，有趣的相亲。有趣的苦恼  有趣的哭泣。

吴：大致明白了。

张：恩恩，是这样的。你这一个是神一样的观察员。

> 后面聊天中总结出两个「一体两面」概念，一是「起落一体」二是「自嘲自嗨一体两面」

### 总结：

以上讨论解决了「有趣」的界定，如何判断「有趣」的问题、对BP商业计划商业盈利模式有了探讨、对线下听众稀少困境等问题。此次讨论对「有趣青年」的项目核心有了大量刺激输出。非常感谢吴楠同学的帮助，刺激和讨论。大家还有对于此有想法的可以写到下面。

之后，咱们会根据以上讨论，下周4月17日-20日由海良我出提纲。另外本周日4月17日确定分工，请大家周六讨论，周日我确定后提交github。

请各位没晚登陆查看、提交想法。

**Comment by aJiea** [comment]
周六讨论可以发起活动issue，时间地点平台。
1对1，寻找有趣的人，在行平台推荐。http://www.zaih.com/  模式一般1对1 但是里面的运营和玩法可以参考。
